services:
  - type: web
    name: landsat-program
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /briefing
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
